pipeline {

    agent any

    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                git credentialsId: 'github-creds',
                    url: 'https://github.com/JANAPRIYA-Bme/cicd-end-to-end',
                    branch: 'main'
            }
        }

        stage('Build Docker') {
            steps {
                script {
                    sh '''
                        echo 'Buid Docker Image'
                        docker build -t manijana123/cicd-e2e:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts') {
            steps {
                script {
                    sh '''
                        echo 'Push to Repo'
                        docker push manijana123/cicd-e2e:${BUILD_NUMBER}
                    '''
                }
            }
        }

        stage('Checkout K8S manifest SCM') {
            steps {
                git credentialsId: 'github-creds',
                    url: 'https://github.com/JANAPRIYA-Bme/cicd-demo-manifests-repo.git',
                    branch: 'main'
            }
        }

        stage('Update K8S manifest & push to Repo') {
            steps {
                script {
                    withCredentials([
                        usernamePassword(
                            credentialsId: 'github-creds',
                            passwordVariable: 'GIT_PASSWORD',
                            usernameVariable: 'GIT_USERNAME'
                        )
                    ]) {
                        sh '''
                            cat deploy.yml
                            sed -i "s|image: manijana123/cicd-e2e:.*|image: manijana123/cicd-e2e:${BUILD_NUMBER}|" deploy.yml
                            cat deploy.yml

                            git config user.name "Jenkins"
                            git config user.email "jenkins@example.com"
                            git add deploy.yml

                            if git diff --cached --quiet; then
                                echo "No changes to commit"
                            else
                                git commit -m "Update deploy.yml to image ${BUILD_NUMBER}"
                                git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/JANAPRIYA-Bme/cicd-demo-manifests-repo.git HEAD:main
                            fi
                        '''
                    }
                }
            }
        }
    }
}

